pyproject.toml, src/doritostats/analytic_utils.py, src/doritostats/simulation_utils.py
If a league has N teams, it is not necessarily true that the team IDs are (0, 1, 2, 3, ... N-1). Sometimes (I think if a league previously had more than N teams and then deleted some), there could be a team_id that is > N. This change gets rid of this naiive idea that team IDs are ordered.
=> Fix team id issue

fantasy_stats/urls.py, fantasy_stats/views.py, src/doritostats/django_utils.py, src/doritostats/simulation_utils.py, templates/fantasy_stats/league.html, templates/fantasy_stats/simulation.html
On top of seeing the expected number of wins & playoff odds for each team, there is now a second table that shows the breakdown of the likelihood of each team finishing in each position at the end of the season.
=> feat: Add final standings distribution to webpage

.gitignore, fantasy_stats/views.py, pyproject.toml, src/doritostats/django_utils.py, src/doritostats/simulation_utils.py, templates/fantasy_stats/simulation.html
A third table is added to the simulations page. This table shows the odds of the following outcomes for each team:
*First place in the league
* First in their division
* Make playoffs
* Last in their division
* Last place in the league
=> feat: Add seeding outcomes table to simulations page

pyproject.toml, src/doritostats/django_utils.py, src/doritostats/simulation_utils.py, templates/fantasy_stats/simulation.html
Remove clipping of all playoff odds and instead leave a disclaimer that simulation results are empirically derived and no not necessarily mean that team has been mathematically eliminated from or clinched the playoffs.
=> fix: don't playoff odds

pyproject.toml, src/doritostats/fetch_utils.py
ESPN keeps changing their API and screwing everything up. They replaced `.owner()` with the SWID. So now we manually fetch and replace the SWIDs with actual names.
=> fix: Set team owners manually

fantasy_stats/views.py, pyproject.toml, src/doritostats/analytic_utils.py, src/doritostats/django_utils.py, src/doritostats/draft_utils.py, src/doritostats/fetch_utils.py, src/doritostats/simulation_utils.py, templates/fantasy_stats/league.html, templates/fantasy_stats/simulation.html
Adds a table detailing the remaining strength of schedule for each team. This table is displayed on the league homepage and simulations page.
=> feat: Add "remaining strength of schedule" table to sites

pyproject.toml, src/doritostats/analytic_utils.py
I think this fixes an issue. For some leagues, the SOS by all metrics was the same for every metric
=> fix: Incorrectly calculating SOS

pyproject.toml, src/doritostats/analytic_utils.py
I incorrectly fixed a problem that didn't exist. It was just a strange edge case where half the league had the exact same schedule as each other and the other half had the same schedule as each other. This was just a weird coincidence
=> fix: Rollback previous SOS chage

fantasy_stats/views.py, pyproject.toml, src/doritostats/analytic_utils.py, src/doritostats/fetch_utils.py, src/doritostats/simulation_utils.py
The entire codebase is written to assume that the variable `week` is synonymous with the word `matchup_period`. This is not inherently true, as some matchup periods span multiple weeks. Rather than re-write the entire codebase to use matchup_period, week is instead defined as the matchup_period at the top of the stack.
=> fix: Use `matchup_period` as week

doritostats/urls.py, pyproject.toml, src/doritostats/analytic_utils.py, src/doritostats/scrape_team_stats.py, src/doritostats/simulation_utils.py, tests/test_analytic_utils.py, tests/test_luck_index.py
The following was introduced by PR #99 when `League.box_scored()` was cached. This stops the `League` object from being pickle-able when trying to run a function in parallel. This PR resolves this issue by temporarily clearing that function during simulations.
```python
PicklingError at /fantasy_stats/simulation/2023/1086064/n_simulations=250
Could not pickle the task to send it to the workers.
```
There was also a bug in how remaining strength of schedule was calculated that has been fixed.
=> fix: Resolve simulations bug and SOS

fantasy_stats/email_notifications/email.py, pyproject.toml
Error when new leagues are created and an email notification is being sent:
```
>>> ValueError: Cannot pass a datetime or Timestamp with tzinfo with the tz parameter. Use tz_convert instead.
>>> File "/app/fantasy_stats/views.py", line 111, in league_input
>>> send_new_league_added_alert(league_info)
>>> File "/app/fantasy_stats/email_notifications/email.py", line 32, in send_new_league_added_alert
>>> pd.Timestamp(league_info.created_date, tz="UTC")
>>> File "pandas/_libs/tslibs/timestamps.pyx", line 1681, in pandas._libs.tslibs.timestamps.Timestamp.__new__
>>> ValueError: Cannot pass a datetime or Timestamp with tzinfo with the tz parameter. Use tz_convert instead.
```
=> fix: Timestamp issue

.gitignore, fantasy_stats/views.py, pyproject.toml, src/doritostats/analytic_utils.py, src/doritostats/django_utils.py, src/doritostats/simulation_utils.py, templates/fantasy_stats/league.html, templates/fantasy_stats/simulation.html, tests/test_analytic_utils.py
The weeks to include in the strength calculation, and the schedule calculation were not correct. Now also display on the webpage what weeks are included in the SOS
=> fix: Remaining SOS was still incorrect

fantasy_stats/views.py, pyproject.toml
Email alerts were getting sent even when existing leagues were being added (even though they already existed in the db)
=> fix: Only send email alerts for new leagues

fantasy_stats/views.py, pyproject.toml, src/doritostats/analytic_utils.py, templates/fantasy_stats/league.html
Display on the UI all players that were started by an owner despite being on bye or inactive that week
=> feat: Add naughty list to the UI

pyproject.toml, src/doritostats/luck_index.py
A team's opponent's luck factors were not being subtracted from the team's luck. They were instead being considered as luck of the same sign for the team.
=> fix: Count opponent luck as unluck for team

pyproject.toml, templates/fantasy_stats/season_stats.html, templates/fantasy_stats/simulation.html
Remove League ID from page titles to make it easier to see total usage of different page types
=> fix: Simplify page names

pyproject.toml, src/doritostats/analytic_utils.py, src/doritostats/django_utils.py
1. The worst score in season records would include weeks that had not been played yet (and had a score of 0)
2. In the final week of the regular season, only a single simulation was being run
=> fix: Worst score & simulations error

fantasy_stats/email_notifications/email.py, fantasy_stats/email_notifications/new_league_added.txt, fantasy_stats/views.py, pyproject.toml, src/doritostats/exceptions.py, src/doritostats/fetch_utils.py, templates/fantasy_stats/index.html
There is a weird bug in the UI that is somehow copying old leagues that don't actually exist. Now, when a user tries to add a league, it will have to be activated first.
=> fix: Only add new leagues if they are active

frontend/src/components/BoxScoresTable.js, frontend/src/components/LuckIndexTable.js, frontend/src/components/NaughtyList.js, frontend/src/components/PowerRankingsTable.js, frontend/src/components/StandingsTable.js, frontend/src/components/WeekSelector.js, frontend/src/components/WeeklyAwardsTable.js, frontend/src/components/styles/league.css, frontend/src/pages/LeaguePage.js
* Each table containing stats has a loading spinner while the API fetches the data. However, the LeaguePage cannot render at all until at least the `/api/league-settings/` and `/api/check-league-status` calls finish. This will render a prettier loading spinner for the entire page while the API is called.
* When LeaguePage is first loading, the different tables display a loading spinner until the respective API calls have fetched data. However, when the `selectedWeek` is updated, the loading spinner was not updated. Instead, the Week headers and URL were changed, and then a few seconds later (when the new data was fetched), the tables would update. This fixes that so that the tables display loading spinners when `selectedWeek` is updated.
Playoff simulations are NOT included in this …
=> Add loading spinners

backend/src/doritostats/django_utils.py, backend/src/doritostats/fetch_utils.py, backend/src/doritostats/scrape_player_stats.py, frontend/src/components/PlayoffOddsTable.js, frontend/src/components/RankDistributionTable.js, frontend/src/components/RemainingStrengthOfScheduleTable.js, frontend/src/components/SeasonPositionalRecordsTable.js, frontend/src/components/SeasonTeamRecordsTable.js, frontend/src/components/SeedingOutcomesTable.js, frontend/src/pages/LeagueSimulationPage.js
* Update the `OWNERS_MAP` with Marco's new name
* Add `week` when scraping player data
* Fix bug when appending series to dataframes
* Updates to the league simulations page
* Make a variable `MIN_WEEK_TO_SIMULATE` to hold this value
* Add a spinner for the entire page while settings are fetched so that page loads instantly (even if there is no data yet)
* Fix bug with the `WeekSelector` where the selected week in the dropdown did not update when changed
* Add a `pendingData` variable to the tables indicating if the data is complete or not
* Move number formating out of the backend API and into the frontend
* Update the season record tables' width
=> Frontend updates to `LeagueSimulationsPage` and `SeasonRecordsPage`
